import { NextRequest, NextResponse } from 'next/server';
import { extractTextFromPDF } from '@/lib/extractText';
import { parseResumeWithAI } from '@/lib/aiParser';
import { MOCK_PORTFOLIO_DATA } from '@/lib/mockData';

export const maxDuration = 60; // Allow up to 60 seconds for AI processing

export async function POST(request: NextRequest) {
    try {
        const formData = await request.formData();
        const file = formData.get('resume') as File | null;
        const rawTextFromForm = formData.get('rawText') as string | null;
        const useMock = formData.get('mock') === 'true';

        let parsedData;

        if (useMock || !process.env.OPENAI_API_KEY) {
            // Mock mode — use sample data (without the AI rewritten fields)
            parsedData = { ...MOCK_PORTFOLIO_DATA };
            // remove fields that would normally be generated by aiWriter
            delete (parsedData as any).headline;
            delete (parsedData as any).bio;
            delete (parsedData as any).summary;
            delete (parsedData as any).experienceNarrative;
            delete (parsedData as any).projectShowcase;
        } else {
            // Real mode — process the uploaded PDF or raw text
            if (!file && !rawTextFromForm) {
                return NextResponse.json(
                    { error: 'No resume file or text provided' },
                    { status: 400 }
                );
            }

            let rawText = '';

            if (file) {
                // Validate file type
                if (file.type !== 'application/pdf') {
                    return NextResponse.json(
                        { error: 'Please upload a PDF file' },
                        { status: 400 }
                    );
                }

                // Validate file size (max 10MB)
                if (file.size > 10 * 1024 * 1024) {
                    return NextResponse.json(
                        { error: 'File size must be less than 10MB' },
                        { status: 400 }
                    );
                }

                // Step 1: Extract text from PDF
                const buffer = Buffer.from(await file.arrayBuffer());
                rawText = await extractTextFromPDF(buffer);
            } else if (rawTextFromForm) {
                rawText = rawTextFromForm;
            }

            if (!rawText || rawText.trim().length < 50) {
                return NextResponse.json(
                    { error: 'Could not extract enough text. Please provide more content.' },
                    { status: 400 }
                );
            }

            // Step 2: AI parse into structured data
            parsedData = await parseResumeWithAI(rawText);
        }

        return NextResponse.json({
            parsedData,
        });
    } catch (error) {
        console.error('Parse error:', error);
        const message = error instanceof Error ? error.message : 'An unexpected error occurred';
        return NextResponse.json({ error: message }, { status: 500 });
    }
}
